# Generated by Django 3.0.3 on 2020-03-20 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_auto_20200319_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='cloudiness',
        ),
        migrations.RemoveField(
            model_name='city',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='city',
            name='wind_speed',
        ),
    ]
